language: python
sudo: false
python:
  - "3.3"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database feedthefox_db;' -U postgres
install:
  - pip install -r requirements.txt
  - pip install tox coveralls
env:
  - TOX_ENV=flake8
  - TOX_ENV=tests
script:
  - tox -e $TOX_ENV
after_success:
  - coveralls
